#! /bin/bash

cd projects
python create_research_list.py
git add projs.js
cd ..

git add index.html 
git add research.html 
git add cv.html 
git add more.html 
git add cv.pdf

git commit -m "automatic update"

git push origin master
